package tn.tunisiana.customer.model;

// default package
// Generated Sep 25, 2013 12:39:34 PM by Hibernate Tools 4.0.0

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Offer generated by hbm2java
 */
@Entity
@Table(name = "offer", catalog = "tunisianaDb")
public class Offer implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private int idoffer;
	private String offerName;
	private String description;
	private List<Correspondance> correspondances;
	private List<Customer> customers;

	public Offer() {
	}

	public Offer(int idoffer) {
		this.idoffer = idoffer;
	}

	public Offer(int idoffer, String offerName, String description) {
		this.idoffer = idoffer;
		this.offerName = offerName;
		this.description = description;
	}

	@Id
	@Column(name = "idoffer", unique = true, nullable = false)
	public int getIdoffer() {
		return this.idoffer;
	}

	public void setIdoffer(int idoffer) {
		this.idoffer = idoffer;
	}

	@Column(name = "offerName", length = 45)
	public String getOfferName() {
		return this.offerName;
	}

	public void setOfferName(String offerName) {
		this.offerName = offerName;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offre")
	public List<Correspondance> getCorrespondances() {
		return correspondances;
	}

	public void setCorrespondances(List<Correspondance> correspondances) {
		this.correspondances = correspondances;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "offres")
	public List<Customer> getCustomers() {
		return customers;
	}

	public void setCustomers(List<Customer> customers) {
		this.customers = customers;
	}
	
	

}
